"""Generate synthetic test xcassets catalog.

Creates tests/ref_samples/Catalog.xcassets with:
- 15 RGBA imagesets (Img001-Img015) at various sizes
- 5 LA imagesets (Img016-Img020) at various sizes
- 3 template-rendering imagesets (among the above)
- 1 AppIcon appiconset with all macOS sizes
All images are solid-color PNGs generated by PIL.
"""

import json
import os
import shutil

from PIL import Image


def generate():
    base = os.path.join(os.path.dirname(__file__), "ref_samples", "Catalog.xcassets")

    if os.path.exists(base):
        shutil.rmtree(base)
    os.makedirs(base)

    # Root Contents.json
    _write_json(os.path.join(base, "Contents.json"),
                {"info": {"author": "xcode", "version": 1}})

    # RGBA imagesets
    rgba_specs = [
        ("Img001", 16, 16, (200, 50, 50, 255)),
        ("Img002", 16, 16, (50, 200, 50, 255)),
        ("Img003", 16, 16, (50, 50, 200, 255)),
        ("Img004", 20, 20, (200, 200, 50, 255)),
        ("Img005", 20, 20, (200, 50, 200, 255)),
        ("Img006", 24, 24, (50, 200, 200, 255)),
        ("Img007", 24, 24, (150, 100, 50, 255)),
        ("Img008", 32, 32, (100, 150, 200, 255)),
        ("Img009", 32, 32, (200, 100, 150, 255)),
        ("Img010", 48, 48, (80, 80, 80, 255)),
        ("Img011", 64, 64, (120, 180, 60, 255)),
        ("Img012", 64, 64, (60, 120, 180, 255)),
        ("Img013", 128, 30, (180, 60, 120, 255)),  # Non-square
        ("Img014", 128, 30, (60, 180, 120, 255)),  # Non-square
        ("Img015", 10, 14, (140, 70, 210, 255)),    # Small non-square
    ]

    # LA imagesets
    la_specs = [
        ("Img016", 12, 12, (100, 255)),
        ("Img017", 12, 12, (150, 255)),
        ("Img018", 18, 18, (200, 255)),
        ("Img019", 8, 12, (128, 255)),
        ("Img020", 64, 64, (80, 255)),
    ]

    # Template rendering for some
    templates = {"Img016", "Img017", "Img018"}

    # Original rendering intent (explicit)
    originals = {"Img001", "Img002", "Img003", "Img008", "Img011"}

    for name, w, h, color in rgba_specs:
        rendering = None
        if name in templates:
            rendering = "template"
        elif name in originals:
            rendering = "original"
        _create_imageset(base, name, w, h, "RGBA", color, rendering=rendering)

    for name, w, h, color in la_specs:
        rendering = None
        if name in templates:
            rendering = "template"
        elif name in originals:
            rendering = "original"
        _create_imageset(base, name, w, h, "LA", color, rendering=rendering)

    # AppIcon appiconset
    _create_appiconset(base, "AppIcon")

    print(f"Generated {base}")
    imagesets = [d for d in os.listdir(base) if d.endswith(".imageset")]
    iconsets = [d for d in os.listdir(base) if d.endswith(".appiconset")]
    print(f"  {len(imagesets)} imagesets, {len(iconsets)} appiconsets")


def _create_imageset(base, name, w, h, mode, color, rendering=None):
    iset = os.path.join(base, f"{name}.imageset")
    os.makedirs(iset)

    Image.new(mode, (w, h), color).save(os.path.join(iset, f"{name}.png"))
    Image.new(mode, (w * 2, h * 2), color).save(
        os.path.join(iset, f"{name}@2x.png"))

    contents = {
        "images": [
            {"filename": f"{name}.png", "idiom": "mac", "scale": "1x"},
            {"filename": f"{name}@2x.png", "idiom": "mac", "scale": "2x"},
        ],
        "info": {"author": "xcode", "version": 1},
    }

    if rendering:
        contents["properties"] = {"template-rendering-intent": rendering}

    _write_json(os.path.join(iset, "Contents.json"), contents)


def _create_appiconset(base, name):
    iset = os.path.join(base, f"{name}.appiconset")
    os.makedirs(iset)

    sizes = [
        ("icon_16x16.png", 16, "1x", "16x16"),
        ("icon_16x16@2x.png", 32, "2x", "16x16"),
        ("icon_32x32.png", 32, "1x", "32x32"),
        ("icon_32x32@2x.png", 64, "2x", "32x32"),
        ("icon_128x128.png", 128, "1x", "128x128"),
        ("icon_128x128@2x.png", 256, "2x", "128x128"),
        ("icon_256x256.png", 256, "1x", "256x256"),
        ("icon_256x256@2x.png", 512, "2x", "256x256"),
        ("icon_512x512.png", 512, "1x", "512x512"),
        ("icon_512x512@2x.png", 1024, "2x", "512x512"),
    ]

    images = []
    for filename, px, scale, size in sizes:
        # Gradient-like icon: shade depends on size
        shade = min(255, px // 4 + 50)
        color = (shade, shade // 2, shade // 3, 255)
        Image.new("RGBA", (px, px), color).save(os.path.join(iset, filename))
        images.append({
            "filename": filename,
            "idiom": "mac",
            "scale": scale,
            "size": size,
        })

    _write_json(os.path.join(iset, "Contents.json"),
                {"images": images, "info": {"author": "xcode", "version": 1}})


def _write_json(path, data):
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
        f.write("\n")


if __name__ == "__main__":
    generate()
